---
abstract: 'Creates a DB connection from a configuration file'
author:
  - 'Sebastien Aperghis-Tramoni <sebastien@aperghis.net>'
build_requires:
  Module::Build: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Connect-FromConfig
provides:
  DBIx::Connect::FromConfig:
    file: lib/DBIx/Connect/FromConfig.pm
    version: 0.07
requires:
  Carp: 0
  DBI: 0
  perl: 5
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
